FROM python:3.7

WORKDIR /alertbot
COPY . /alertbot

ENV PYTHONPATH="$PYTHONPATH:/alertbot/alertbot"

RUN pip3 install -r /alertbot/requirements.txt -r /alertbot/requirements-production.txt

CMD ["/bin/bash", "/alertbot/heroku.sh"]